#version 430 core

// Since each cell is 1 workgroup we only need 1 local invocation
layout (local_size_x = 1, local_size_y = 1) in;

// Cell type constants
const int EMPTY = 0;
const int STONE = 1;
const int SAND = 2;
const int WATER = 3;
const int GAS = 4;

struct Cell {
    int type;
};

// To prevent race conditions we use 2 grids.
// We read from the input grid and write to the output grid
// We only swap the grids after all cells in the grid were written.
layout(std430, binding = 0) buffer InputBuffer { Cell cells[]; } inputGrid;
layout(std430, binding = 1) buffer OutputBuffer { Cell cells[]; } outputGrid;

uniform int width;
uniform int height;
uniform int pass;// 0 for even workgroups, 1 for odd workgroups

bool isInBounds(ivec2 p) {
    return p.x >= 0 && p.x < width && p.y >= 0 && p.y < height;
}

int getCellType(ivec2 p) {
    if (!isInBounds(p)) return -1;
    int idx = p.y * width + p.x;
    return inputGrid.cells[idx].type;
}

bool isEmpty(ivec2 p) {
    return isInBounds(p) && getCellType(p) == EMPTY;
}

// Returns true if the POWDER cell will move out.
// Checks below -> down right -> down left
bool shouldMoveOutPowder(ivec2 p) {
    if (isEmpty(p + ivec2(0, -1))) return true;// down
    if (isEmpty(p + ivec2(1, -1))) return true;// down-right
    if (isEmpty(p + ivec2(-1, -1))) return true;// down-left
    return false;
}

// Returns true if the LQIUID cell will move out.
// Checks below -> down right -> down left -> right -> left
bool shouldMoveOutLiquid(ivec2 p) {
    if (isEmpty(p + ivec2(0, -1))) return true;// down
    if (isEmpty(p + ivec2(1, -1))) return true;// down-right
    if (isEmpty(p + ivec2(-1, -1))) return true;// down-left
    if (isEmpty(p + ivec2(1, 0))) return true;// right
    if (isEmpty(p + ivec2(-1, 0))) return true;//left
    return false;
}

// Returns the type of the particle that should move into this position.
// The heart of the "pull" method.
// Checks above -> up-left -> up-right (powders + liquids)
// Then left -> right (liquids + smoke)
// TODO Then below -> down-left -> down-right (smoke)
int getIncomingType(ivec2 p) {
    ivec2 nextCellPos = p;

    // Check above
    nextCellPos = p + ivec2(0, 1);
    if (isInBounds(nextCellPos)) {
        int above = getCellType(nextCellPos);
        if (above == SAND || above == WATER) return above;
    }


    // Check up-left
    nextCellPos = p + ivec2(-1, 1);
    if (isInBounds(nextCellPos)) {
        int upLeft = getCellType(nextCellPos);
        if ((upLeft == SAND || upLeft == WATER) &&
        !isEmpty(nextCellPos + ivec2(0, -1)))
        return upLeft;
    }


    // Check up-right
    nextCellPos = p + ivec2(1, 1);
    if (isInBounds(nextCellPos)) {
        int upRight = getCellType(nextCellPos);
        if ((upRight == SAND || upRight == WATER) &&
        !isEmpty(nextCellPos + ivec2(0, -1)) &&
        !isEmpty(nextCellPos + ivec2(1, -1)))
        return upRight;
    }


    // Check left (water only moves horizontally if it can't move down/down-left/down-right)
    nextCellPos = p + ivec2(-1, 0);
    if (isInBounds(nextCellPos)) {
        int left = getCellType(nextCellPos);
        if ((left == WATER) &&
        !isEmpty(nextCellPos + ivec2(0, -1)) &&
        !isEmpty(nextCellPos + ivec2(0, -1))) {
            return left;
        }
    }


    // Check right (water only moves horizontally if it can't move down/down-left/down-right AND can't move right)
    nextCellPos = p + ivec2(1, 0);
    if (isInBounds(nextCellPos)) {
        int right = getCellType(nextCellPos);
        if ((right == WATER) &&
        !isEmpty(nextCellPos + ivec2(0, -1))) {
            return right;
        }
    }

    return EMPTY;
}

void main() {
    ivec2 workGroupID = ivec2(gl_WorkGroupID.xy);

    // Skip workgroups based on pass
    int checkerboard = (workGroupID.x + workGroupID.y) % 2;
    if (checkerboard != pass) {
        return;
    }

    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    if (pos.x >= width || pos.y >= height) return;

    int idx = pos.y * width + pos.x;
    int type = inputGrid.cells[idx].type;
    int nextType = type;

    switch (type) {
        case EMPTY:// Empty cells pull cells into them
        nextType = getIncomingType(pos);
        break;

        // Other cell types decide if they should vacate
        case SAND:
        if (shouldMoveOutPowder(pos)) nextType = EMPTY;
        break;

        case WATER:
        if (shouldMoveOutLiquid(pos)) nextType = EMPTY;
        break;

        case STONE:
        break;
    }

    outputGrid.cells[idx].type = nextType;
}